config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :watches
  devise_for :users

  # get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :watches

  def self.ransackable_attributes(auth_object = nil)
    ["admin", "created_at", "email",  "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["watches"]
  end
end

app/models/watch.rb
class Watch < ApplicationRecord
    enum category: { standard: 0, premium: 1, premium_plus: 2 }
    belongs_to :user

    scope :filter_by_name, -> (name) { where("lower(name) like ?", "#{name.downcase}%")}
    scope :filter_by_price_min, -> (price_min) { where("price >= ?", price_min)}
    scope :filter_by_price_max, -> (price_max) { where("price <= ?", price_max)}
    scope :filter_by_category, -> (category) { where category: category }

    def self.ransackable_attributes(auth_object = nil)
        ["category", "created_at", "description", "id", "id_value", "name", "photo_url", "price", "updated_at", "user_id"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["user"]
    end
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization
    protect_from_forgery with: :null_session

end

app/controllers/concerns/orderable.rb
module Orderable
  extend ActiveSupport::Concern

  module ClassMethods
  end

  # A list of the param names that can be used for ordering the model list
  def ordering_params(params)
    # For example it retrieves a list of watches in descending order of price.
    # Within a specific price, watches are ordered ascending by name
    #
    # GET /watches?sort=-price, name
    # ordering_params(params) # => { price: :desc, name: :asc }
    # Experience.order(price: :desc, name: :asc)
    #
    ordering = {}
    
    if params[:sort]
      sort_order = { '+' => :asc, '-' => :desc }

      sorted_params = params[:sort].split(',')
      sorted_params.each do |attr|
        sort_sign = (attr =~ /\A[+-]/) ? attr.slice!(0) : '+'
        model = controller_name.classify.constantize
        
        if model.attribute_names.include?(attr)
          ordering[attr] = sort_order[sort_sign]
        end
      end
    end
    
    ordering
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
include Orderable

  before_action :set_watch, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authorize_user, only: [:destroy]

  # GET /watches or /watches.json
  # GET /watches?name=a 
  # GET /watches?price_min=1
  # GET /watches?price_max=100 
  # GET /watches?category=0,1,2 
  def index
    # @watches = Watch.all

    @watches = Watch.where(nil) # creates an anonymous scope
    @watches = @watches.filter_by_name(params[:name]) if params[:name].present?
    @watches = @watches.filter_by_price_min(params[:price_min]) if params[:price_min].present?
    @watches = @watches.filter_by_price_max(params[:price_max]) if params[:price_max].present?
    @watches = @watches.filter_by_category(params[:category]) if params[:category].present?

    @watches = @watches.order(ordering_params(params)).all

    # render json: @watches
  end
 
  # GET /watches/1 or /watches/1.json
  def show
  end

  # # GET /watches/new
  def new
    # @watch = Watch.new
    @watch = current_user.watches.build
  end

  # GET /watches/1/edit
  def edit
  end

  # POST /watches or /watches.json
  def create
    # @watch = Watch.new(watch_params)
    @watch = current_user.watches.build(watch_params)

    # if @watch.save
    #   render json: @watch
    # else
    #   render json: {error: 'Error creating watch'}
    # end

    respond_to do |format|
      if @watch.save
        format.html { redirect_to watch_url(@watch), notice: "Watch was successfully created." }
        format.json { render :show, status: :created, location: @watch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @watch.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /watches/1 or /watches/1.json
  def update
    # @watch = Watch.find(params[:id])
        # if @post.update(watch_params)
        #     render json: @watch
        # else
        #     render json: {error: 'Error updating watch'}
        # end

        respond_to do |format|
          if @watch.update(watch_params)
            format.html { redirect_to watch_url(@watch), notice: "Watch was successfully updated." }
            format.json { render :show, status: :ok, location: @watch }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @watch.errors, status: :unprocessable_entity }
          end
        end
  end

  # DELETE /watches/1 or /watches/1.json
  def destroy
    # @watch = Watch.find(params[:id])
    # if @watch.destroy
    #     render status: :ok
    # else
    #     render json: {error: 'Error deleting watch'}
    # end

    @watch.destroy!

    respond_to do |format|
      format.html { redirect_to watch_url, notice: "Watch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @watch = current_user.watches.find_by(id: params[:id])
  end

  private

    def authorize_user
      watch = @watch || Watch
      authorize watch
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_watch
      @watch = Watch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def watch_params
      params.require(:watch).permit(:name, :description, :category, :price, :photo_url, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/home/index.html.erb
<h1>Watches App</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watches</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    #  <p class="notice"><%= notice %></p>
    #  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/watches/_form.html.erb
<%= form_with(model: watch) do |form| %>
  <% if watch.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(watch.errors.count, "error") %> prohibited this watch from being saved:</h2>

      <ul>
        <% watch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category, Watch.categories.keys %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :photo_url, style: "display: block" %>
    <%= form.text_field :photo_url %>
  </div>

   <div>
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :friend_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/watches/_watch.html.erb
<div id="<%= dom_id watch %>">
  <p>
    <strong>Name:</strong>
    <%= watch.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= watch.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= watch.category %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= watch.price %>
  </p>

  <p>
    <strong>Photo url:</strong>
    <%= watch.photo_url %>
  </p>

</div>

app/views/watches/edit.html.erb
<h1>Editing watch</h1>

<%= render "form", watch: @watch %>

<br>

<div>
  <%= link_to "Show this watch", @watch %> |
  <%= link_to "Back to watches", watches_path %>
</div>

app/views/watches/index.html.erb
<h1>Watches</h1>

<div id="watches">
  <% @watches.each do |watch| %>
    <%= render watch %>
    <p>
      <%= link_to "Show this watch", watch %>
    </p>
  <% end %>
</div>

<%= link_to "New watch", new_watch_path %>

app/views/watches/new.html.erb
<h1>New watch</h1>

<%= render "form", watch: @watch %>

<br>

<div>
  <%= link_to "Back to watches", watches_path %>
</div>

app/views/watches/show.html.erb
<%= render @watch %>

<div>
  <%= link_to "Edit this watch", edit_watch_path(@watch) %> |
  <%= link_to "Back to watches", watches_path %>

  <%= button_to "Destroy this watch", @watch, method: :delete %>
</div>